version: '3.8'

services:
  db-admin-tool:
    build: .
    ports:
      - "8008:8008"
    environment:
      - NODE_ENV=production
      - PORT=8008
    env_file:
      - .env
    restart: unless-stopped 