version: '3.8'

services:
  db-admin-tool:
    build: .
    ports:
      - "8008:8008"
    environment:
      - NODE_ENV=production
      - PORT=8008
    volumes:
      - ./sessions:/app/sessions
    restart: unless-stopped 